version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: happs
      MYSQL_ROOT_PASSWORD: password1900
    networks:
      - app-network
  app:
    depends_on:
      - mysql
      - redis
    build: 
      context: .
      dockerfile: Dockerfile
    image: happs
    container_name: app
    restart: unless-stopped
    command: bash -c "php artisan migrate --seed && /usr/sbin/apache2ctl -D FOREGROUND"
    tty: true
    env_file:
    - .env
    ports:
      - "80:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local